name: another test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo 1
          sleep 3
          echo 2
          sleep 3
          echo 6
          sleep 3
          echo 6
          sleep 60
