name: another test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python -c "
          import time,os
          for i in range(1):
            time.sleep(3)
            os.system('echo '+str(i))
          "
          exit 1
