name: another test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - run: |
          python -hc "
          import time,os
          for i in range(30):
            time.sleep(3)
            print(i)
            os.system('echo '+str(i))
          "
