name: another test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python << EOL
          import time
          for i in range(1):
            time.sleep(3)
            print(i)
          EOL
          exit 1
        shell: sh
