name: another test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          . scl_source enable llvm-toolset-6.0 || true
          python << EOL
          import time
          for i in range(20):
            time.sleep(3)
            print(i)
          EOL
