name: another test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python << EOL || true
          import time
          for i in range(20):
            time.sleep(3)
            print(i)
          EOL
        shell: sh
