name: another test
on: [workflow_dispatch]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - run: |
          python << EOL
          import time
          for i in range(10):
            time.sleep(3)
            print(i)
          time.sleep(60)
          EOL
